main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('sign-up/', views.sign_up, name='sign_up'),
    path("logout/", views.LogOut, name="logout"),
    path('create-post/', views.create_post, name='create_post')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    path("", include('django.contrib.auth.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + "\n" + self.description

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description"]

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from .forms import RegisterForm, PostForm
from django.contrib.auth.models import User, Group
from .models import Post
from django.contrib import messages

@login_required(login_url="/login")
def home(request):
    posts = Post.objects.all()
    if request.method == 'POST':
        post_id = request.POST.get('post-id')
        user_id = request.POST.get('user-id')

        if post_id:
            post = Post.objects.filter(id=post_id).first()
            if post and (post.author == request.user or request.user.has_perm("main.delte_post")):
                post.delete()
        elif user_id:
            user = User.objects.filter(id=user_id).first()
            if user and request.user.is_staff:
                try:
                    group = Group.objects.get(name="default")
                    group.user_set.remove(user)
                except:
                    pass
                try:
                    group = Group.objects.get(name="mod")
                    group.user_set.remove(user)
                except:
                    pass

    return render(request, 'main/home.html', {'posts':posts})

def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect('/home')
    else:
        form = RegisterForm()

    return render(request, 'registration/sign_up.html', {'form': form})

def LogOut(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("login")


@login_required(login_url="/login")
@permission_required('main.add_post', login_url="/login", raise_exception=True)
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "the post has created successfully!")
            return redirect("/home")
    else:
        form = PostForm()
    
    return render(request, "main/create_post.html", {"form":form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{% block title %}My Site{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-post">Post</a>
            </li>
          </ul>
        </div>
        <div>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <span class="navbar-text">Logged in as {{user.username}} | </span>
            <li class="nav-item">
              <a class="nav-link" href="/logout">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/sign_up">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container m-auto mt-2 messages">
      {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
          {% endfor %}
      {% endif %}
    </div>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function(){
            setTimeout(function(){
                $('.messages').fadeOut('slow');
            }, 2000);
        });
    </script>
  </body>
</html>

templates/main/create_post.html
{% extends 'base.html' %} 
{% block title %}Create a Post{% endblock %} 
{% load crispy_forms_tags %} 

{% block content %}
<form method="post" class="m-5">
  {% csrf_token %}{{form|crispy}}
  <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

templates/main/home.html
{%extends 'base.html'%}
{%block title%}Home Page{%endblock%}
{%block content%}
    {% for post in posts%}
        <div class="card mt-2">
            <div class="card-header"><strong>@{{post.author.username}}</strong></div>
            <div class="card-body d-f flex-row justify-content-between">
                <div>
                    <h5 class="card-title">{{post.title}}</h5>
                    <p>{{post.description}}</p>
                </div>
                <div class="d-flex">
                    {% if user == post.author or perms.main.delete_post %}
                        <form method="post">
                            {% csrf_token %}
                            <button
                            type="submit"
                            class="btn btn-danger"
                            name="post-id"
                            value="{{post.id}}"
                            >
                            Delete
                            </button>
                        </form>
                    {% endif %}
                    {%if user.is_staff%}
                        <form method="post" class="mx-2">
                            {% csrf_token %}
                            <button
                            type="submit"
                            class="btn btn-warning"
                            name="user-id"
                            value="{{post.author.id}}"
                            >
                            Ban User
                            </button>
                        </form>
                    {%endif%}
                </div>
            </div>
            <div class="card-footer text-muted">
                {{post.created_at}}
            </div>
        </div>
        {%empty%}
        <p>No posts yet !</p>
    {%endfor%}
{%endblock%}